apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: auto-playlist
spec:
  project: default
  source:
    # chart: sealed-secrets
    repoURL: https://github.com/jkleve/auto-playlist
    targetRevision: HEAD
    # helm:
    #   releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: auto-playlist
