version: '3.3'


services:
  api:
    build: ./playlist_manager
    image: jkleve/auto-playlist:latest
    ports:
     - "5001:5001"
    networks:
     - cluster-network
    environment:
     - PYTHONUNBUFFERED=1  # @todo turn off if production
    labels: 
      kompose.service.type: loadbalancer
    # @todo use args to set FLASK_ENV=development
    # environment:
    #  - NGINX_HOST=foobar.com
    #  - NGINX_PORT=80

  plivo:
    build: ./plivo
    image: jkleve/plivo:latest
    ports:
     - "5002:5002"
    networks:
     - cluster-network
    environment:
     - PYTHONUNBUFFERED=1
    labels: 
      kompose.service.type: loadbalancer

networks:
  cluster-network:
