version: '3.3'

services:
  api:
    build: ./playlist_manager
    image: jkleve/auto-playlist:latest
    ports:
     - "8081:8081"
    networks:
     - cluster-network
    environment:
     - PYTHONUNBUFFERED=1
     - FLASK_ENV=development

  plivo:
    build: ./plivo
    image: jkleve/plivo:latest
    ports:
     - "5002:5002"
    networks:
     - cluster-network
    environment:
     - PYTHONUNBUFFERED=1
     - FLASK_ENV=development

  redis:
    image: redis:6.2.6-alpine
    ports:
      - '6379:6379'
    networks:
      - cluster-network


networks:
  cluster-network:
