version: '3.3'


services:
  api:
    build: ./playlist_manager
    image: jkleve/auto-playlist:latest
    ports:
     - "8081:8081"
    networks:
     - cluster-network
    environment:
     - PYTHONUNBUFFERED=1
     - FLASK_ENV=development

  plivo:
    build: ./plivo
    image: jkleve/plivo:latest
    ports:
     - "5002:5002"
    networks:
     - cluster-network
    environment:
     - PYTHONUNBUFFERED=1
     - FLASK_ENV=development

networks:
  cluster-network:
