version: '3.3'

services:
  api:
    build:
      context: ./playlist_manager
      dockerfile: Dockerfile.test
    volumes:
      - ./playlist_manager:/app
    # environment:
    #  - PYTHONUNBUFFERED=1
    #  - FLASK_ENV=development

  # plivo:
  #   build:
  #     context: ./plivo
  #     dockerfile: Dockerfile.test

  # redis:
  #   image: redis:6.2.6-alpine
  #   ports:
  #     - '6379:6379'
  #   networks:
  #     - cluster-network


networks:
  cluster-network:
